Register-ScheduledTask `
    -TaskName 'AutoHotkey' `
    -Trigger (New-ScheduledTaskTrigger `
        -AtLogOn `
        -User $env:USERNAME) `
    -Action (New-ScheduledTaskAction `
        -Execute 'powershell' `
        -Argument '-NoProfile -WindowStyle Hidden "while ($true) { autohotkey dotfiles.ahk }"' `
        -WorkingDirectory $PSScriptRoot) `
    -Settings (New-ScheduledTaskSettingsSet `
        -DontStopOnIdleEnd `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -ExecutionTimeLimit 0) `
    -RunLevel Highest `
    -Force
