function wg { run winget @args }
function wgc { wg configure @args }
function wgd { wg download @args }
function wge { wg export @args }
function wgf { wg features @args }
function wgh { wg hash @args }
function wgi { wg install @args }
function wgip { wg import @args }
function wgl { wg list @args }
function wgp { wg pin @args }
function wgr { wg repair @args }
function wgs { wg search @args }
function wgset { wg settings @args }
function wgsrc { wg source @args }
function wgsw { wg show @args }
function wgu { wg uninstall @args }
function wgug { wg upgrade @args }
function wgv { wg validate @args }
